version: '3.1'

services:
  web:
    image: nginx:latest
    ports:
      - "3009:80"
    volumes:
      - .:/var/www/html
      - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
      - app
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html
#      - ./docker/php/etc:/usr/local/etc/php
    depends_on:
      - db
    ports:
      - "9230:9000"
  db:
    image: mariadb:10.5
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=splice
      - MYSQL_USER=cr
      - MYSQL_PASSWORD=ChateaRougeForTea
    ports:
      - "30336:3306"
    volumes:
      - .:/var/www/html
      - crdata:/var/lib/mysql
volumes:
  crdata:
